CreateConVar("GrenadeCarryEnabled", 1, 128, "Enable the Grenade Carry function")
CreateConVar("GrenadeCarryNPC", 1, 128, "Enable the Grenade Carry function for NPC's")
CreateConVar("GrenadeCarryChance", 20, 128, "Chance for an NPC to drop a live grenade. Value is percentage chance")
CreateConVar("GrenadeCarryNoDupes", 1, 128, "Prevent NPCs from dropping multiple grenades")
CreateConVar("GrenadeCarryHitbox", 1, 128, "Which part of the NPC has to be hit to drop a grenade.\n- 1 = Chest and stomach\n- 2 = Chest\n- 3 = Stomach")
CreateConVar("GrenadeCarryNoElite", 0, 128, "Prevent Combine Elites from dropping grenades.")
CreateConVar("GrenadeCarryBrokenHitgroups", 0, 128, "Workaround for models that do not support chest and stomach hitgroups.")
CreateConVar("GrenadeCarryBrokenHitgroupsPlayer", 0, 128, "Workaround for models that do not support chest and stomach hitgroups.")

CreateConVar("GrenadeCarryPhysical", 0, 128, "Enable NPCs carrying physical grenades on their bodies, which can be shot.")
CreateConVar("GrenadeCarryPhysicalPly", 0, 128, "Enable Players carrying physical grenades on their bodies, which can be shot.")
CreateConVar("GrenadeCarrySide", 0, 128, "Which side should the NPCs carried grenade be on?\n- 0 = Left\n- 1 = Right.")
CreateConVar("GrenadeCarrySidePlayer", 0, 128, "Which side should the Players carried grenade be on?\n- 0 = Left\n- 1 = Right.")

CreateConVar("GrenadeCarryPlayer", 1, 128, "Enable the Grenade Carry function for players")
CreateConVar("GrenadeCarryPlayerHeld", 1, 128, "Grenades can also be shot out of a players hand.")
CreateConVar("GrenadeCarryPlayerChance", 20, 128, "Chance for a player to drop a live grenade. Value is percentage chance")
CreateConVar("GrenadeCarryPlayerHitbox", 1, 128, "Which part of the player has to be hit to drop a grenade.\n- 1 = Chest and stomach\n- 2 = Chest\n- 3 = Stomach")
CreateConVar("GrenadeCarryRequireAmmo", 1, 128, "Player must have ammo for the grenade to drop a grenade.")
CreateConVar("GrenadeCarryRemoveAmmo", 1, 128, "Remove a grenade from the player when dropping a grenade.")