hook.Add( "PopulateToolMenu", "ItemIconsMenu", function()
	spawnmenu.AddToolMenuOption( "Options", "CoolIcons", "ItemIconsMenu", "CoolIcons", "", "", function( panel )
	panel:ClearControls()
	panel:NumSlider( "Grenade Warning Distance", "GrenadeWarningDistance", 0, 3000, 0 )
	panel:Help( "Distance at which the grenade warning is visible" )
	panel:NumSlider( "Item Icon Distance", "ItemIconDistance", 0, 3000, 0 )
	panel:Help( "Distance at which item icons are visible" )
	panel:NumSlider( "Item Icon Size", "IconSize", 1, 16, 0 )
	panel:Help( "Size of all icons" )
	panel:CheckBox( "See Icons through walls", "SeeThruWalls" )
	panel:CheckBox( "Enable Icon Outlines", "IconOutlines" )
	panel:CheckBox( "Enable Weapon Icons", "WeaponIcon" )
	panel:CheckBox( "Use Custom Weapon Icon", "CustomWeaponIcon" )
	panel:CheckBox( "Enable Ammo Icons", "AmmoIcon" )
	panel:CheckBox( "Enable Ammo Crate Icons", "AmmoCrateIcon" )
	panel:CheckBox( "Use Custom Ammo Icon", "CustomAmmoIcon" )
	panel:CheckBox( "Enable Health Icons", "HealthIcon" )
	panel:CheckBox( "Enable Health Charger Icons", "HealthChargerIcon" )
	panel:CheckBox( "Use Custom Health Icon", "CustomHealthIcon" )
	panel:CheckBox( "Enable Armor Icons", "ArmorIcon" )
	panel:CheckBox( "Enable Suit Charger Icons", "SuitChargerIcon" )
	panel:CheckBox( "Use Custom Armor Icon", "CustomArmorIcon" )
	panel:CheckBox( "Enable Grenade Warning Icons", "GrenadeWarningIcon" )
	panel:CheckBox( "Use Custom Grenade Warning Icon", "CustomGreWarIcon" )
	panel:CheckBox( "Enable Grenade Ammo Icons", "GrenadeIcon" )
	panel:CheckBox( "Use Custom Grenade Ammo Icon", "CustomGrenadeIcon" )
	panel:CheckBox( "Enable Rocket Ammo Icons", "RocketIcon" )
	panel:CheckBox( "Use Custom Rocket Ammo Icon", "CustomRocketIcon" )
	panel:Help( "Custom Images" )
	panel:Help( "If custom icon is enabled, paste a material path to the relevant textbox. Use .PNG or .JPG files. Transparent backgrounds are preferred." )
	panel:Help( "Example path: 'icons/coolfolder/coolicon.png'" )

	panel:TextEntry( "Ammo icon", "CustomAmmoIconImage" )
	panel:TextEntry( "Armor icon", "CustomArmorIconImage" )
	panel:TextEntry( "Health icon", "CustomHealthIconImage" )
	panel:TextEntry( "Grenade Warning icon", "CustomGreWarIconImage" )
	panel:TextEntry( "Grenade icon", "CustomGrenadeIconImage" )
	panel:TextEntry( "Weapon icon", "CustomWeaponIconImage" )
	panel:TextEntry( "Rocket icon", "CustomRocketIconImage" )
end)
end)