CreateClientConVar("AmmoColorR", "227", true, false, "Red color value of the ammo icon", 0, 255)
CreateClientConVar("AmmoColorG", "166", true, false, "Green color value of the ammo icon", 0, 255)
CreateClientConVar("AmmoColorB", "0", true, false, "Blue color value of the ammo icon", 0, 255)
CreateClientConVar("AmmoColorA", "255", true, false, "Alpha (transparency) value of the ammo icon", 0, 255)

CreateClientConVar("ArmorColorR", "0", true, false, "Red color value of the armor icon", 0, 255)
CreateClientConVar("ArmorColorG", "212", true, false, "Green color value of the armor icon", 0, 255)
CreateClientConVar("ArmorColorB", "255", true, false, "Blue color value of the armor icon", 0, 255)
CreateClientConVar("ArmorColorA", "255", true, false, "Alpha (transparency) value of the health icon", 0, 255)

CreateClientConVar("HealthColorR", "0", true, false, "Red color value of the health icon", 0, 255)
CreateClientConVar("HealthColorG", "255", true, false, "Green color value of the health icon", 0, 255)
CreateClientConVar("HealthColorB", "0", true, false, "Blue color value of the health icon", 0, 255)
CreateClientConVar("HealthColorA", "255", true, false, "Alpha (transparency) value of the health icon", 0, 255)

CreateClientConVar("GreWarColorR", "255", true, false, "Red color value of the grenade warning icon", 0, 255)
CreateClientConVar("GreWarColorG", "0", true, false, "Green color value of the grenade warning icon", 0, 255)
CreateClientConVar("GreWarColorB", "0", true, false, "Blue color value of the grenade warning icon", 0, 255)
CreateClientConVar("GreWarColorA", "255", true, false, "Alpha (transparency) value of the grenade warning icon", 0, 255)

CreateClientConVar("WeaponColorR", "255", true, false, "Red color value of the weapon icon", 0, 255)
CreateClientConVar("WeaponColorG", "255", true, false, "Green color value of the weapon icon", 0, 255)
CreateClientConVar("WeaponColorB", "255", true, false, "Blue color value of the weapon icon", 0, 255)
CreateClientConVar("WeaponColorA", "255", true, false, "Alpha (transparency) value of the weapon icon", 0, 255)

CreateClientConVar("RocketColorR", "255", true, false, "Red color value of the rocket icon", 0, 255)
CreateClientConVar("RocketColorG", "255", true, false, "Green color value of the rocket icon", 0, 255)
CreateClientConVar("RocketColorB", "255", true, false, "Blue color value of the rocket icon", 0, 255)
CreateClientConVar("RocketColorA", "255", true, false, "Alpha (transparency) value of the ammo icon", 0, 255)

hook.Add( "PopulateToolMenu", "ItemIconsColorMenu", function()
	spawnmenu.AddToolMenuOption( "Options", "CoolIcons", "ItemIconColorMenu", "CoolIcons Colors", "", "", function( panel )
	panel:ClearControls()
	panel:ColorPicker( "Ammo Icon Color", "AmmoColorR", "AmmoColorG", "AmmoColorB", "AmmoColorA" )
	panel:Help( "Color picker for the Ammo Icon" )
	panel:Help( "Default is R 227 G 166 B 0 A 255" )
	panel:ColorPicker( "Armor Icon Color", "ArmorColorR", "ArmorColorG", "ArmorColorB", "ArmorColorA" )
	panel:Help( "Color picker for the Armor Icon" )
	panel:Help( "Default is R 0 G 212 B 255 A 255" )
	panel:ColorPicker( "Health Icon Color", "HealthColorR", "HealthColorG", "HealthColorB", "HealthColorA" )
	panel:Help( "Color picker for the Health Icon" )
	panel:Help( "Default is R 0 G 255 B 0 A 255" )
	panel:ColorPicker( "Grenade Warning Icon Color", "GreWarColorR", "GreWarColorG", "GreWarColorB", "GreWarColorA" )
	panel:Help( "Color picker for the Grenade Warning Icon" )
	panel:Help( "Default is R 255 G 0 B 0 A 255" )
	panel:ColorPicker( "Weapon Icon Color", "WeaponColorR", "WeaponColorG", "WeaponColorB", "WeaponColorA" )
	panel:Help( "Color picker for Weapon and Grenade Icons" )
	panel:Help( "Default is R 255 G 255 B 255 A 255" )
	panel:ColorPicker( "Rocket Icon Color", "RocketColorR", "RocketColorG", "RocketColorB", "RocketColorA" )
	panel:Help( "Color picker for Rocket Icons" )
	panel:Help( "Default is R 255 G 255 B 255 A 255" )
end)
end)